### PR TITLE
[Core][Channel] Minor re-arrangement of Channel internal primitives

### PR DESCRIPTION
**Pull request by ddmbr**

### CODE REVIEW

**Comment by kygx-legend** [comment]
Looks better.

**Comment by Yuzhen11** [comment]
Apply this to all the channels? BroadcastChannel? 
And `flush` method can be removed I think.

**Comment by ddmbr** [comment]
My intention is to expose two lower-level primitives. `flush` is a higher-level shortcut and I think it should be there.

**Comment by Yuzhen11** [comment]
There's already an `out` function there.

**Comment by ddmbr** [comment]
OK. My understanding is that `in` and `out` are two higher-level methods. Below these two, there are lower-level methods, and each channel may have their own specific methods. Do you agree? And for methods other than these three categories we can depreciate them gradually.

**Comment by Yuzhen11** [comment]
Yes, I agree.

**Comment by ddmbr** [comment]
I'll merge this first and polish all other channels in following PRs.

**Pull request merged**
