### PR TITLE
[Core] Add an ObjListPool, LRU Cache, FIFO Cache to support swapping of ObjLists later

### PR DESCRIPTION
**Pull request by lmatz**
issue #256
Open a pull request for discussion and changes.

### CODE REVIEW

**Comment by kygx-legend** [comment]
```
mongo_server=172.16.105.13:20001`
mongo_db=hdb
mongo_collection=enwiki
```

**Comment by lmatz** [comment]
@kygx-legend 
it throws "terminate called after throwing an instance of 'mongo::SocketException'
  what():  socket exception [FAILED_STATE] for 172.16.105.13:20001 (172.16.105.13) failed"
cannot connect to 172.16.105.13:20001?

**Comment by kygx-legend** [comment]
Oh I see. You're using proj10 so you can not connect to workers. There's another mongo cluster on proj5-10. Please use `proj5:20001` instead.

**Comment by lmatz** [comment]
Now if I want to update the pull request, I should merge my 'dev' branch with 'experimental' before pushing?

**Comment by kygx-legend** [comment]
I think so. But it's better to use rebase, not merge.

**Comment by kygx-legend** [comment]
Since this change does affect many parts and it's not stable, the work will be moved to the branch in https://github.com/kygx-legend/husky/tree/em. So close this then.

**Pull request closed without merging**
