### PR TITLE
[IO][Input] Add an Input Format for local files NFSLineInputFormat(#3)

### PR DESCRIPTION
**Pull request by ydwu4**
#3 [IO][Input] Add an Input Format for local files NFSLineInputFormat.
@ddmbr @kygx-legend @Yuzhen11  Please review.

### CODE REVIEW

**Comment by Yuzhen11** [comment]
Looks good. Can you provide an example to demo how to use the nfs_input_format?

**Comment by ydwu4** [comment]
Sure! I've added the NFS word count example.

**Comment by Yuzhen11** [comment]
Looks good to me. I think it's ready to merge. 

Other issues include：

1. The example is almost the same with wc-mr.cpp... We may not need such a redundant example. 
2. Current architecture of inpuformat and filesplitter is a little bit messy. May try to improve the whole inputformat architecture later. May follow hadoop inputformat style.

**Comment by ydwu4** [comment]
Removed the word count nfs example.

**Comment by kygx-legend** [comment]
Could you solve the conflicts and use `husky` namespace out of `io`?

**Comment by ddmbr** [comment]
I think we should use just one LineInputFormat. By plugging in NFSFileSplitter and HDFSFileSplitter we get NFSLineInputFormat and HDFSLineInputFormat. So there will be only line_input_format.cpp and line_input_format.hpp.

@Yuzhen11 @kygx-legend

**Comment by ydwu4** [comment]
I just resolved the namespace huksy conflict.

**Comment by kygx-legend** [comment]
You may run `scripts/lint.py` and `scripts/check-clang-format.sh` then.

**Comment by ydwu4** [comment]
Just modified the code style according to lint.py and clang-format.sh.

**Comment by ddmbr** [comment]
How about we merge this PR first, and then do another to unify LineInputFormat? @Yuzhen11 @kygx-legend

**Comment by kygx-legend** [comment]
Agree

**Pull request merged**
