### PR TITLE
[PageRank Example] Second token getting skipped when parsing input lines

### PR DESCRIPTION
**Pull request by aminmkhan**
After reading Vertex ID, avoid Tokenizer iterator getting incremented twice

### CODE REVIEW

**Comment by lmatz** [comment]
Maybe it is due to different file format? 
"src : dst1 dst2"
"src dst1 dst2"

**Comment by kygx-legend** [comment]
Right. To cope with different format is just to write different parsing function.

**Comment by kygx-legend** [comment]
Could you help add comment there instead of this modification? Thanks a lot.

**Comment by aminmkhan** [comment]
> Maybe it is due to different file format?
> "src : dst1 dst2"
> "src dst1 dst2"


To handle such different formats in my opinion, better approach would be to update separators:

https://github.com/husky-team/husky/blob/eda5e3aaf8cf795dfbd90ee5ddece44907ccb664/examples/pagerank.cpp#L55

For example:

```cpp
        boost::char_separator<char> sep(" \t,:;");
```

**Comment by kygx-legend** [comment]
This approach is okay for me but if any other operator?

**Comment by zzxx-husky** [comment]
Emm.. That `it++` may be to skip the number of neighbors. I think the program assumes the format of each line is : `source num_neighbors neighbor_1 neighbor_2 ... neighbor_n`. This format is quite common by the way.

**Comment by aminmkhan** [comment]
Agree to all your points, without any comments this could be confusing, especially when working with different file formats. Updated with more comments.

https://github.com/husky-team/husky/blob/6e72d9cb26b55afda4307239f50c534f27781395/examples/pagerank.cpp#L55-L62

**Review by kygx-legend — APPROVED** [review]

**Comment by kygx-legend** [comment]
Thanks for the fixing!

**Pull request merged**
