### PR TITLE
[Master] Clean up deprecated code in Master and add ProgressTracker

### PR DESCRIPTION
**Pull request by ddmbr**
ProgressTracker is to track the progress of workers. Workers need to report progress to master in a non-blocking way. At the moment it will only check whether the workers have finished their work, and halt the Master if so.

### CODE REVIEW

**Comment by ddmbr** [comment]
@kygx-legend @zzxx-husky @Yuzhen11 Please review!

**Comment by kygx-legend** [comment]
That's quite cool. It's strange that a link error in travis ci.

**Comment by Yuzhen11** [comment]
Seems that I couldn't find progress_tracker.cpp?

**Comment by kygx-legend** [comment]
LGTM.

**Pull request merged**
