### PR TITLE
[IO][Input] Support ORCInputFormat and add Cube application

### LINKED ISSUE #260: Move ORCInputFormat to branch experimental
Since the branch `experimental` is created, it's time to move ORCInputFormat into that.

### PR DESCRIPTION
**Pull request by kygx-legend**
Resolve #260

### CODE REVIEW

**Comment by kygx-legend** [comment]
@ClydeZhao could you please help check this?

**Comment by ClydeZhao** [comment]
Got a warning when building `Master`
```
[ 95%] Building CXX object master/CMakeFiles/husky-master-objs.dir/orc_assigner.cpp.o
In file included from /data/ruihao/github/husky/master/orc_assigner.hpp:24:0,
                 from /data/ruihao/github/husky/master/orc_assigner.cpp:17:
/data/ruihao/github/husky/io/input/orc_hdfs_inputstream.hpp: In member function 'virtual void husky::io::HDFSFileInputStream::read(void*, uint64_t, uint64_t)':
/data/ruihao/github/husky/io/input/orc_hdfs_inputstream.hpp:64:59: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
             nbytes = hdfsRead(hdfs_fs_, hdfs_file_, buf + start, remain);
```

**Comment by kygx-legend** [comment]
@ClydeZhao This warning can be ignored.

**Comment by kygx-legend** [comment]
@ClydeZhao Could you help check the code once again? If no other problems, I'll merge this.

**Pull request merged**
