### PR TITLE
[Core][Mailbox] Fix a bug in _recv_comm_handler by adding lock_guard

### PR DESCRIPTION
**Pull request by Yuzhen11**

### CODE REVIEW

**Comment by Yuzhen11** [comment]
In _recv_comm_handler of MailboxEventLoop, we update the *pred* required by the LocalMailbox without lock. So there may be a case when the MailboxEventLoop notifies the LocalMailbox before the LocalMailbox waits, which will cause the LocalMailbox always waits for the cv even though the messages are there. This PR fixes the problem.

**Comment by Yuzhen11** [comment]
Also move the notify functions out from the callback function (set_comm_available_handler and set_comm_complete_handler).

**Comment by kygx-legend** [comment]
Can we check if the other parts also has this problem?

**Comment by ddmbr** [comment]
I think Mailbox does not have this problem now.

**Pull request merged**
