### PR TITLE
[Husky] Update Accessor, Shuffler & Aggregator

### PR DESCRIPTION
**Pull request by zzxx-husky**
Fix issue #39
1. New implementation of Aggregator. Aggregator contains the logic related to aggregation only,
   and it is independent of context information, Accessor, Channel and even multi-thread tools.
   But in order to use Aggregator, a complete factory HuskyAggregatorFactory needs to be assembled.
   And this factory will be registered to AggregatorFactory when the program starts.
2. Add a new tool: CounterBarrier. Units can choose whether to wait for the counter of the barrier to reach
   the target count. When target count is reached, the barrier will notify all the waiting units.
3. Add a new tool: GenerationLock. Units will keep waiting if their generation is ahead of the global
   generation. A unit can increase the global generation and then waiting units are notified.
4. Add a new tool: CallOnceEachTime, sharing the same base class with GenerationLock. The class
   implementation of this is to have different CallOnceEachTime objects for different groups of threads.

### CODE REVIEW

**Comment by kygx-legend** [comment]
LGTM.

**Comment by kygx-legend** [comment]
Ping @ddmbr

**Comment by kygx-legend** [comment]
@Yuzhen11 @lijinf2 Please give comments.
@zzxx-husky Could you please add this to wiki?

**Comment by Yuzhen11** [comment]
Need time to read....

**Comment by zzxx-husky** [comment]
@kygx-legend Wiki for aggregator is added. Kindly take a look.

**Comment by ddmbr** [comment]
Do you need to modify the root CMakeLists.txt as well so that `make husky` includes Aggregator components?

**Comment by zzxx-husky** [comment]
@ddmbr As I've checked, aggregator is inside lib-objs and lib-objs is part of husky already. (⊙.⊙)

**Pull request merged**
